// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: asd.proto

#ifndef PROTOBUF_asd_2eproto__INCLUDED
#define PROTOBUF_asd_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace pt2 {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_asd_2eproto();
void protobuf_AssignDesc_asd_2eproto();
void protobuf_ShutdownFile_asd_2eproto();

class asd;

// ===================================================================

class asd : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pt2.asd) */ {
 public:
  asd();
  virtual ~asd();

  asd(const asd& from);

  inline asd& operator=(const asd& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const asd& default_instance();

  void Swap(asd* other);

  // implements Message ----------------------------------------------

  inline asd* New() const { return New(NULL); }

  asd* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const asd& from);
  void MergeFrom(const asd& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(asd* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string a = 1;
  bool has_a() const;
  void clear_a();
  static const int kAFieldNumber = 1;
  const ::std::string& a() const;
  void set_a(const ::std::string& value);
  void set_a(const char* value);
  void set_a(const char* value, size_t size);
  ::std::string* mutable_a();
  ::std::string* release_a();
  void set_allocated_a(::std::string* a);

  // required int32 s = 2;
  bool has_s() const;
  void clear_s();
  static const int kSFieldNumber = 2;
  ::google::protobuf::int32 s() const;
  void set_s(::google::protobuf::int32 value);

  // required int32 d = 3;
  bool has_d() const;
  void clear_d();
  static const int kDFieldNumber = 3;
  ::google::protobuf::int32 d() const;
  void set_d(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:pt2.asd)
 private:
  inline void set_has_a();
  inline void clear_has_a();
  inline void set_has_s();
  inline void clear_has_s();
  inline void set_has_d();
  inline void clear_has_d();

  // helper for ByteSize()
  int RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr a_;
  ::google::protobuf::int32 s_;
  ::google::protobuf::int32 d_;
  friend void  protobuf_AddDesc_asd_2eproto();
  friend void protobuf_AssignDesc_asd_2eproto();
  friend void protobuf_ShutdownFile_asd_2eproto();

  void InitAsDefaultInstance();
  static asd* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// asd

// required string a = 1;
inline bool asd::has_a() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void asd::set_has_a() {
  _has_bits_[0] |= 0x00000001u;
}
inline void asd::clear_has_a() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void asd::clear_a() {
  a_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_a();
}
inline const ::std::string& asd::a() const {
  // @@protoc_insertion_point(field_get:pt2.asd.a)
  // return a_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  return a_.GetNoArena();
}
inline void asd::set_a(const ::std::string& value) {
  set_has_a();
  a_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pt2.asd.a)
}
inline void asd::set_a(const char* value) {
  set_has_a();
  a_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pt2.asd.a)
}
inline void asd::set_a(const char* value, size_t size) {
  set_has_a();
  a_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pt2.asd.a)
}
inline ::std::string* asd::mutable_a() {
  set_has_a();
  // @@protoc_insertion_point(field_mutable:pt2.asd.a)
  return a_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* asd::release_a() {
  // @@protoc_insertion_point(field_release:pt2.asd.a)
  clear_has_a();
  return a_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void asd::set_allocated_a(::std::string* a) {
  if (a != NULL) {
    set_has_a();
  } else {
    clear_has_a();
  }
  a_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), a);
  // @@protoc_insertion_point(field_set_allocated:pt2.asd.a)
}

// required int32 s = 2;
inline bool asd::has_s() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void asd::set_has_s() {
  _has_bits_[0] |= 0x00000002u;
}
inline void asd::clear_has_s() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void asd::clear_s() {
  s_ = 0;
  clear_has_s();
}
inline ::google::protobuf::int32 asd::s() const {
  // @@protoc_insertion_point(field_get:pt2.asd.s)
  return s_;
}
inline void asd::set_s(::google::protobuf::int32 value) {
  set_has_s();
  s_ = value;
  // @@protoc_insertion_point(field_set:pt2.asd.s)
}

// required int32 d = 3;
inline bool asd::has_d() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void asd::set_has_d() {
  _has_bits_[0] |= 0x00000004u;
}
inline void asd::clear_has_d() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void asd::clear_d() {
  d_ = 0;
  clear_has_d();
}
inline ::google::protobuf::int32 asd::d() const {
  // @@protoc_insertion_point(field_get:pt2.asd.d)
  return d_;
}
inline void asd::set_d(::google::protobuf::int32 value) {
  set_has_d();
  d_ = value;
  // @@protoc_insertion_point(field_set:pt2.asd.d)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace pt2

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_asd_2eproto__INCLUDED
